### ISSUE TITLE
Plugin causes Prettier to crash whenever input is not coming from an actual file

### ISSUE THREAD

**Issue by farmerpaul** [electrovir/prettier-plugin-multiline-arrays#18]
Thank you for creating this plugin, it's just what I was looking for!

However we use Prettier in multiple places in our project where it's not just being fed a file to be formatted, but rather a string (which lacks a filename). When that's the case, `options.filepath` is `undefined`, which causes this plugin to crash:

```
[REDACTED]/node_modules/prettier-plugin-multiline-arrays/dist/printer/multiline-array-printer.js:15
            if (options.filepath.endsWith('package.json') &&
                                 ^

TypeError: Cannot read properties of undefined (reading 'endsWith')
    at Proxy.<anonymous> ([REDACTED]/node_modules/prettier-plugin-multiline-arrays/dist/printer/multiline-array-printer.js:15:34)
    at callPluginPrintFunction ([REDACTED]/node_modules/prettier/index.js:8417:26)
    at mainPrintInternal ([REDACTED]/node_modules/prettier/index.js:8366:22)
    at [REDACTED]/node_modules/prettier/index.js:8358:32
    at AstPath.call ([REDACTED]/node_modules/prettier/index.js:8175:24)
    at mainPrint ([REDACTED]/node_modules/prettier/index.js:8358:21)
    at printModuleSpecifier ([REDACTED]/node_modules/prettier/index.js:27826:16)
    at printPathNoParens ([REDACTED]/node_modules/prettier/index.js:29497:18)
    at Object.genericPrint [as print] ([REDACTED]/node_modules/prettier/index.js:29322:23)
    at Proxy.<anonymous> ([REDACTED]/node_modules/prettier-plugin-multiline-arrays/dist/printer/multiline-array-printer.js:14:58)
```

In one part of our project, we are able to pass an empty string (`''`) as the value of the `filepath` option to work around this issue (because we authored the code where `prettier.format()` is being called and can make that change), however I just discovered that other npm scripts that we have, including running Storybook to launch our component library previewer, crashes with the same error (I guess it's also running Prettier behind the scenes?). I don't know how to work around it for Storybook.

**Comment by farmerpaul** [comment]
@electrovir thanks for following up! Do you foresee any issues with my PR? It seems to do the trick fine in my project when I apply that patch manually in my `node_modules`.

In my own project I'm working on, I'm hoping to get a PR in to my colleagues today, but I can't submit it until this issue is fixed (and I'd rather not implement the ugly workaround of targeting my personal repo in my `package.json`).

**Comment by farmerpaul** [comment]
Fantastic, works perfectly here! Thanks very much for the quick fix. 🍻
